### ISSUE TITLE
Is it a Bitvisor lib?

### ISSUE THREAD

**Issue by lonnietc** [mmisono/bitvisor_process_lib#1]
Hello,

I am researching a project for a very Thin hypervisor that would be similar to Bitvisor but in Rust so that it can virtualize the OS (Linux, Windows, etc..) and perform some useful function for the user and I am wondering if your "bitvisor_process_lib" and a port of Bitvisor over to Rust?

Thanks

**Comment by mmisono** [comment]
Hi,

No, this is not a rust version of BitVisor. BitVisor has the functionality to include and execute elf binaries in the ring3 of VMX root-mode. This `bitvisor_process_lib` is an elementary library to create such a binary in Rust.
You can check more details here: https://github.com/mmisono/bitvisor_process_echo (though I'm not sure if this works with the latest versions of BitVisor).

**Comment by lonnietc** [comment]
Thanks for the information on as it is very much appreciated.

On a side note, I want to email you on another discussion related to your paper "Distributed Denial of Service Attack Prevention, at Source Machines (2018)"
